const errorFunction = require("../utils/ErrorFunction");
const OracleDB = require("../services/database");
const { CheckNullInt, DateFormat, CheckNullFloat } = require("../utils/Helper");

const ListTeamRole = `SELECT AT.AUDITOR_ID, SU.USER_NAME, AT.ROLE_ID, R.ROLE_NAME FROM AUD_STAT.STAT_AUDIT_TEAM AT
LEFT JOIN AUD_REG.SYSTEM_USER SU ON AT.AUDITOR_ID = SU.USER_ID
LEFT JOIN AUD_STAT.REF_ROLE R ON AT.ROLE_ID = R.ID
WHERE AT.IS_ACTIVE = 1 AND AT.STAT_AUDIT_ID = :P_ID`;
const AuditStatus = `SELECT P.ID, SA.STATUS, SU.USER_NAME, SU.USER_CODE, 
SU1.USER_ID APPROVED_FIRST_ID, SU1.USER_NAME APPROVED_FIRST_NAME, SU1.USER_CODE APPROVED_FIRST_CODE, P.APPROVED_FIRST_DATE,
SU2.USER_ID APPROVED_SECOND_ID, SU2.USER_NAME APPROVED_SECOND_NAME, SU2.USER_CODE APPROVED_SECOND_CODE, P.APPROVED_SECOND_DATE,
SU3.USER_ID APPROVED_THIRD_ID, SU3.USER_NAME APPROVED_THIRD_NAME, SU3.USER_CODE APPROVED_THIRD_CODE, P.APPROVED_THIRD_DATE
FROM AUD_STAT.STAT_AUDIT SA
LEFT JOIN AUD_STAT.STAT_AUDIT_PROCESS P ON SA.ID = P.STAT_AUDIT_ID
LEFT JOIN AUD_REG.SYSTEM_USER SU ON P.SAVED_BY = SU.USER_ID
LEFT JOIN AUD_REG.SYSTEM_USER SU1 ON P.APPROVED_FIRST_ID = SU1.USER_ID
LEFT JOIN AUD_REG.SYSTEM_USER SU2 ON P.APPROVED_SECOND_ID = SU2.USER_ID
LEFT JOIN AUD_REG.SYSTEM_USER SU3 ON P.APPROVED_THIRD_ID = SU3.USER_ID
WHERE SA.ID = :P_ID`;
const FindIDs = `SELECT DEPARTMENT_ID, FP.PERIOD_ID FROM AUD_STAT.STAT_AUDIT SA 
INNER JOIN AUD_STAT.REF_PERIOD P ON SA.PERIOD_ID = P.ID
INNER JOIN FAS_ADMIN.REF_PERIOD FP ON P.PERIOD_YEAR = FP.YEAR_LABEL
WHERE SA.ID = :P_ID`;

module.exports = {
  async BM1List(req, res) {
    try {
      let paramID = {};
      paramID.P_ID = parseInt(req.body.ID, 10);

      const resultFindID = await OracleDB.simpleExecute(FindIDs, paramID);

      let params = {};
      params.P_PERIOD_ID = resultFindID.rows[0]?.PERIOD_ID;
      params.P_DEPARTMENT_ID = resultFindID.rows[0]?.DEPARTMENT_ID;

      let ListQuery = `SELECT 
      BM1.ID,
      FAS.FAS_AUDIT_ID AUDIT_ID,
      FAS.AUDIT_TYPE_ID,
      FAS.AUDIT_TYPE_NAME,
      FAS.AUDIT_NAME,
      FAS.AUDIT_CODE,
      FAS.ENT_NAME,
      FAS.ORG_REGISTER_NO,
      FAS.BUDGET_TYPE_ID,
      FAS.BUDGET_SHORT_NAME,
      FAS.SALBAR_ANGILAL, 
      --HOSLUULAH
      --SEDVIN UNDESLEL
      FAS.FORM_TYPE_ID,
      FAS.AUDIT_TYPE,
      --TATGALZSAN
      BM1.IS_EXPERT_ATTEND,
      BM1.IS_PRESS_REPORT,
      BM1.WORK_PEOPLE,
      BM1.WORK_DAY,
      BM1.WORK_TIME,
      FAS.TUL_BENEFIT,
      FAS.TOD_BENEFIT, 
      FAS.AUDIT_ORG_TYPE,
      FAS.AUDIT_ORG_CHECK_NAME,
      FAS.DEPARTMENT_NAME,
      FAS.CHECK_DEPARTMENT_NAME,
      FAS.AUDIT_DEPARTMENT_NAME,
      FAS.AUDITOR_LEAD,
      FAS.AUDITOR_MEMBER
      
      FROM AUD_STAT.NEW_BM1_DATA BM1
      RIGHT JOIN (SELECT 
      --NEW TABLE ID
      FA.ID FAS_AUDIT_ID,
      RAT.AUDIT_TYPE_ID,
      RAT.AUDIT_TYPE_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ||' - '|| RAT.AUDIT_TYPE_NAME AUDIT_NAME,
      FA.AUDIT_CODE,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ENT_NAME,
      AO.ORG_REGISTER_NO,
      RBT.BUDGET_TYPE_ID,
      RBT.BUDGET_SHORT_NAME,
      RDI.IND_VALUE_NAME SALBAR_ANGILAL, 
      RFT.FORM_TYPE_ID,
      RFT.FORM_TYPE_NAME AUDIT_TYPE,
      C.TUL_BENEFIT,
      NVL(CASE WHEN(CASE WHEN FA.STATUS = 1 AND FA.PERIOD_ID > 3 THEN 3 ELSE FA.AUDIT_FORM_TYPE END) = 1 THEN A.SUO ELSE B.SUO END, 0) + 
      NVL(CASE WHEN(CASE WHEN FA.STATUS = 1 AND FA.PERIOD_ID > 3 THEN 3 ELSE FA.AUDIT_FORM_TYPE END) = 1 THEN D.ZAL_AMOUNT ELSE D1.ZAL_AMOUNT_SAMPLE END, 0) TOD_BENEFIT, 
      FA.AUDIT_ORG_TYPE,
      RAOT.AUDIT_ORG_CHECK_NAME,
      (CASE WHEN RCD.DEPARTMENT_NAME IS NOT NULL AND FA.AUDIT_ORG_TYPE = 1 AND FA.AUDIT_CHECK_DEP_ID IN (101,102) THEN RD.DEPARTMENT_NAME||' - '||RCD.DEPARTMENT_NAME ELSE RD.DEPARTMENT_NAME END) DEPARTMENT_NAME,
      RD.DEPARTMENT_NAME AS CHECK_DEPARTMENT_NAME,
      RD1.DEPARTMENT_NAME AS AUDIT_DEPARTMENT_NAME,
      (SELECT LISTAGG(SU.USER_NAME,', ') WITHIN GROUP(ORDER BY FATD.ID) FROM FAS_ADMIN.FAS_AUDIT_TEAM_DATA FATD INNER JOIN AUD_REG.SYSTEM_USER SU ON FATD.AUDITOR_ID = SU.USER_ID WHERE FATD.FAS_AUDIT_ID = FA.ID AND FATD.ROLE_ID = 2 AND FATD.IS_ACTIVE = 1 GROUP BY FATD.FAS_AUDIT_ID) AUDITOR_LEAD,
      (SELECT LISTAGG(SU.USER_NAME,', ') WITHIN GROUP(ORDER BY FATD.ID) FROM FAS_ADMIN.FAS_AUDIT_TEAM_DATA FATD INNER JOIN AUD_REG.SYSTEM_USER SU ON FATD.AUDITOR_ID = SU.USER_ID WHERE FATD.FAS_AUDIT_ID = FA.ID AND FATD.ROLE_ID = 3 AND FATD.IS_ACTIVE = 1 GROUP BY FATD.FAS_AUDIT_ID) AUDITOR_MEMBER,
      FA.PERIOD_ID
      FROM FAS_ADMIN.FAS_AUDIT FA
      
      INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID
      INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
      LEFT JOIN FAS_ADMIN.ENTITY_NAME EN ON FA.ENT_ID = EN.ENT_ID 
      INNER JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_TYPE RAT ON FA.AUDIT_TYPE = RAT.AUDIT_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_FORM_TYPE RFT ON FA.AUDIT_FORM_TYPE = RFT.FORM_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_ORG_TYPE RAOT ON FA.AUDIT_ORG_TYPE = RAOT.ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD ON FA.USER_DEPARTMENT_ID = RD.DEPARTMENT_ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD1 ON FA.AUDIT_CHECK_DEP_ID = RD1.DEPARTMENT_ID
      LEFT JOIN FAS_ADMIN.REF_CHECK_DEPARTMENT RCD ON FA.AUDIT_CHECK_DEP_ID = RCD.DEPARTMENT_ID AND FA.CHECK_DEPARTMENT_ID = RCD.ID
      LEFT JOIN FAS_ADMIN.FAS_DOCUMENT_DATA FDD2 ON FA.ID = FDD2.FAS_AUDIT_ID AND FDD2.IS_ACTIVE = 1 AND FDD2.IND_ID IN (71,346,437,534)
      LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE RDI ON FDD2.IND_VALUE = RDI.ID
      --START UR UGUUJ
      LEFT JOIN (SELECT FAS_AUDIT_ID, SUM(CASE WHEN INDICATOR_ID IN(228, 672) THEN BENEFIT_RESULT END) TUL_BENEFIT, SUM(CASE WHEN INDICATOR_ID IN (229, 673) THEN BENEFIT_RESULT END) TUL_BUS_BENEFIT 
      FROM FAS_ADMIN.FAS_AUDIT_BENEFIT_DATA
      GROUP BY FAS_AUDIT_ID) C ON FA.ID = C.FAS_AUDIT_ID
      LEFT JOIN (SELECT A.FAS_AUDIT_ID, SUM(CASE WHEN A.UR_UGUUJ_TYPE = 320 THEN A.AMOUNT END) SUO, SUM(CASE WHEN A.UR_UGUUJ_TYPE = 321 THEN A.AMOUNT END) SBUO FROM 
      (SELECT A.FAS_AUDIT_ID,A.ID,A.AMOUNT, C.UR_UGUUJ_TYPE           
      FROM FAS_ADMIN.FAS_DOC_5_1 A
         INNER JOIN FAS_ADMIN.FAS_DOC_5_5 B ON A.ID = B.ID_5_1
         INNER JOIN FAS_ADMIN.FAS_DOC_5_6 C ON A.ID = C.ID_5_1 AND C.IS_CLAUSE = 0
         WHERE A.IS_ACTIVE = 1 AND A.IS_ZALRUULAH = 284 AND B.UR_UGUUJ = 283
      UNION ALL
      SELECT A.FAS_AUDIT_ID,A.ID,A.AMOUNT, B.UR_UGUUJ_TYPE          
      FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
      INNER JOIN FAS_ADMIN.FAS_DOC_5_6 B ON A.ID = B.ID_5_1 AND B.IS_CLAUSE = 1
      WHERE A.IS_ACTIVE = 1 AND A.UR_UGUUJ = 283
      ) A
         GROUP BY A.FAS_AUDIT_ID) A ON FA.ID = A.FAS_AUDIT_ID
         
      LEFT JOIN (SELECT A.FAS_AUDIT_ID, SUM(A.AMOUNT) ZAL_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1 A
        INNER JOIN FAS_ADMIN.FAS_DOC_5_2 B ON A.ID = B.ID_5_1
        INNER JOIN FAS_ADMIN.FAS_DOC_5_6 C ON A.ID = C.ID_5_1
        WHERE A.IS_ACTIVE = 1 AND A.IS_ZALRUULAH = 283 AND B.UR_UGUUJ = 283
      GROUP BY A.FAS_AUDIT_ID) D ON FA.ID = D.FAS_AUDIT_ID
      LEFT JOIN (SELECT A.FAS_AUDIT_ID, SUM(ZAL_AMOUNT_SAMPLE) ZAL_AMOUNT_SAMPLE FROM
      (SELECT A.FAS_AUDIT_ID, A.AMOUNT ZAL_AMOUNT_SAMPLE,A.ID
        FROM FAS_ADMIN.FAS_DOC_5_2_SAMPLE A
        WHERE A.IS_ACTIVE = 1 AND A.UR_UGUUJ = 283
        UNION ALL  
      SELECT  A.FAS_AUDIT_ID, A.AMOUNT ZAL_AMOUNT_SAMPLE, A.ID
      FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
      WHERE A.IS_ACTIVE = 1 AND A.UR_UGUUJ = 283 
      ) A
      INNER JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE C ON A.ID = C.ID_5_2
      GROUP BY A.FAS_AUDIT_ID) D1 ON FA.ID = D1.FAS_AUDIT_ID
        
      LEFT JOIN (SELECT A.FAS_AUDIT_ID, SUM(CASE WHEN A.UR_UGUUJ_TYPE = 320 THEN A.AMOUNT END) SUO, SUM(CASE WHEN A.UR_UGUUJ_TYPE = 321 THEN A.AMOUNT END) SBUO FROM 
      (SELECT A.FAS_AUDIT_ID, A.ID, A.AMOUNT, B.UR_UGUUJ_TYPE
      FROM FAS_ADMIN.FAS_DOC_5_5_SAMPLE A
      INNER JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE B ON A.ID = B.ID_5_5 AND B.IS_CLAUSE = 0
      WHERE A.IS_ACTIVE = 1 AND A.UR_UGUUJ = 283 
      UNION ALL
      SELECT A.FAS_AUDIT_ID,A.ID, A.AMOUNT, B.UR_UGUUJ_TYPE          
      FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
      INNER JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE B ON A.ID = B.ID_5_5 AND B.IS_CLAUSE = 1
      WHERE A.IS_ACTIVE = 1 AND A.UR_UGUUJ = 283 
      ) A
      GROUP BY A.FAS_AUDIT_ID) B ON FA.ID = B.FAS_AUDIT_ID
      --END UR UGUUJ
      
      WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1 AND FA.AUDIT_CHECK_DEP_ID = :P_DEPARTMENT_ID AND FA.PERIOD_ID = :P_PERIOD_ID) FAS ON BM1.AUDIT_ID = FAS.FAS_AUDIT_ID AND BM1.AUDIT_TYPE_ID = FAS.AUDIT_TYPE_ID`;

      ListQuery += `\n ORDER BY BM1.ID`;

      const result = await OracleDB.simpleExecute(ListQuery, params);
      const resultRole = await OracleDB.simpleExecute(ListTeamRole, paramID);
      const resultStatus = await OracleDB.simpleExecute(AuditStatus, paramID);

      return res.send({
        data: result.rows,
        role: resultRole.rows,
        status:
          resultStatus.rows[0] !== undefined ? resultStatus.rows[0] : null,
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM1IU(req, res) {
    try {
      const queryBM1 = `BEGIN AUD_STAT.NEW_BM1_I_U(:P_ID, :P_AUDIT_ID, :P_AUDIT_TYPE_ID, :P_IS_EXPERT_ATTEND, :P_IS_PRESS_REPORT, :P_WORK_PEOPLE, :P_WORK_DAY, :P_WORK_TIME, :P_CREATED_BY); END;`;
      const queryBM1log = `BEGIN AUD_STAT.NEW_BM1_LOG_I_U(:P_ID, :P_AUDIT_ID, :P_AUDIT_TYPE_ID, :P_AUDIT_TYPE_NAME, :P_AUDIT_NAME, :P_AUDIT_CODE, :P_ENT_NAME, :P_ORG_REGISTER_NO, :P_BUDGET_TYPE_ID, :P_BUDGET_SHORT_NAME, :P_SALBAR_ANGILAL, :P_FORM_TYPE_ID, :P_AUDIT_TYPE, :P_AUDIT_ORG_TYPE, :P_AUDIT_ORG_CHECK_NAME, :P_DEPARTMENT_NAME, :P_CHECK_DEPARTMENT_NAME, :P_AUDIT_DEPARTMENT_NAME, :P_AUDIT_LEAD, :P_AUDIT_MEMBER, :P_CREATED_BY); END;`;

      let data = [];
      let log = [];
      function getData(req) {
        if (req.body.data?.length > 0) {
          req.body.data?.forEach((element) => {
            data.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_IS_EXPERT_ATTEND: CheckNullInt(element.IS_EXPERT_ATTEND),
              P_IS_PRESS_REPORT: CheckNullInt(element.IS_PRESS_REPORT),
              P_WORK_PEOPLE: CheckNullInt(element.WORK_PEOPLE),
              P_WORK_DAY: CheckNullInt(element.WORK_DAY),
              P_WORK_TIME: CheckNullInt(element.WORK_TIME),
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        if (req.body.log?.length > 0) {
          req.body.log?.forEach((element) => {
            log.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              //P_BM1_ID: CheckNullInt(element.BM1_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_AUDIT_TYPE_NAME: element.AUDIT_TYPE_NAME,
              P_AUDIT_NAME: element.AUDIT_NAME,
              P_AUDIT_CODE: element.AUDIT_CODE,
              P_ENT_NAME: element.ENT_NAME,
              P_ORG_REGISTER_NO: element.ORG_REGISTER_NO,
              P_BUDGET_TYPE_ID: CheckNullInt(element.BUDGET_TYPE_ID),
              P_BUDGET_SHORT_NAME: element.BUDGET_SHORT_NAME,
              P_SALBAR_ANGILAL: element.SALBAR_ANGILAL,
              P_FORM_TYPE_ID: CheckNullInt(element.FORM_TYPE_ID),
              P_AUDIT_TYPE: element.AUDIT_TYPE,
              P_AUDIT_ORG_TYPE: CheckNullInt(element.AUDIT_ORG_TYPE),
              P_AUDIT_ORG_CHECK_NAME: element.AUDIT_ORG_CHECK_NAME,
              P_DEPARTMENT_NAME: element.DEPARTMENT_NAME,
              P_CHECK_DEPARTMENT_NAME: element.CHECK_DEPARTMENT_NAME,
              P_AUDIT_DEPARTMENT_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_AUDIT_LEAD: element.AUDIT_LEAD,
              P_AUDIT_MEMBER: element.AUDIT_MEMBER,
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        return { data };
      }

      getData(req);

      const result = await OracleDB.multipleExecute(queryBM1, data);
      const resultLog = await OracleDB.multipleExecute(queryBM1log, log);
      return res.send({
        message: "Хадгаллаа.",
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM2List(req, res) {
    try {
      let paramID = {};
      paramID.P_ID = parseInt(req.body.ID, 10);

      const resultFindID = await OracleDB.simpleExecute(FindIDs, paramID);

      let params = {};
      params.P_PERIOD_ID = resultFindID.rows[0]?.PERIOD_ID;
      params.P_DEPARTMENT_ID = resultFindID.rows[0]?.DEPARTMENT_ID;

      let ListQuery = `SELECT 
      FA.ID AUDIT_ID,
      RAT.AUDIT_TYPE_ID,
      RAT.AUDIT_TYPE_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ||' - '|| RAT.AUDIT_TYPE_NAME AUDIT_NAME,
      FA.AUDIT_CODE,
      --SEDVIN UNDESLEL
      RFT.FORM_TYPE_ID,
      RFT.FORM_TYPE_NAME AUDIT_TYPE,
      FA.AUDIT_ORG_TYPE,
      RAOT.AUDIT_ORG_CHECK_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ENT_NAME,
      AO.ORG_REGISTER_NO,
      RBT.BUDGET_TYPE_ID,
      RBT.BUDGET_SHORT_NAME,
      RDI.IND_VALUE_NAME SALBAR_ANGILAL, 
      (CASE WHEN RCD.DEPARTMENT_NAME IS NOT NULL AND FA.AUDIT_ORG_TYPE = 1 AND FA.AUDIT_CHECK_DEP_ID IN (101,102) THEN RD.DEPARTMENT_NAME||' - '||RCD.DEPARTMENT_NAME ELSE RD.DEPARTMENT_NAME END) DEPARTMENT_NAME,
      RD.DEPARTMENT_NAME AS CHECK_DEPARTMENT_NAME,
      RD1.DEPARTMENT_NAME AS AUDIT_DEPARTMENT_NAME
      FROM FAS_ADMIN.FAS_AUDIT FA
      INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID
      INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
      LEFT JOIN FAS_ADMIN.ENTITY_NAME EN ON FA.ENT_ID = EN.ENT_ID 
      INNER JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_TYPE RAT ON FA.AUDIT_TYPE = RAT.AUDIT_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_FORM_TYPE RFT ON FA.AUDIT_FORM_TYPE = RFT.FORM_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_ORG_TYPE RAOT ON FA.AUDIT_ORG_TYPE = RAOT.ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD ON FA.USER_DEPARTMENT_ID = RD.DEPARTMENT_ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD1 ON FA.AUDIT_CHECK_DEP_ID = RD1.DEPARTMENT_ID
      LEFT JOIN FAS_ADMIN.REF_CHECK_DEPARTMENT RCD ON FA.AUDIT_CHECK_DEP_ID = RCD.DEPARTMENT_ID AND FA.CHECK_DEPARTMENT_ID = RCD.ID
      LEFT JOIN FAS_ADMIN.FAS_DOCUMENT_DATA FDD2 ON FA.ID = FDD2.FAS_AUDIT_ID AND FDD2.IS_ACTIVE = 1 AND FDD2.IND_ID IN (71,346,437,534)
      LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE RDI ON FDD2.IND_VALUE = RDI.ID
      WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1
      AND FA.AUDIT_CHECK_DEP_ID = :P_DEPARTMENT_ID AND FA.PERIOD_ID = :P_PERIOD_ID`;

      //ListQuery += `\n ORDER BY BM1.ID`;

      const result = await OracleDB.simpleExecute(ListQuery, params);
      const resultRole = await OracleDB.simpleExecute(ListTeamRole, paramID);
      const resultStatus = await OracleDB.simpleExecute(AuditStatus, paramID);

      return res.send({
        data: result.rows,
        role: resultRole.rows,
        status:
          resultStatus.rows[0] !== undefined ? resultStatus.rows[0] : null,
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM2IU(req, res) {
    try {
      const queryBM2 = `BEGIN AUD_STAT.NEW_BM2_I_U(:P_ID, :P_AUDIT_ID, :P_AUDIT_TYPE_ID, :P_CREATED_BY); END;`;
      const queryBM2log = `BEGIN AUD_STAT.NEW_BM2_LOG_I_U(:P_ID, :P_AUDIT_ID, :P_BM2_ID, :P_AUDIT_TYPE_ID, :P_AUDIT_TYPE_NAME, :P_AUDIT_NAME, :P_AUDIT_CODE, :P_FORM_TYPE_ID, :P_AUDIT_TYPE, :P_AUDIT_ORG_TYPE, :P_AUDIT_ORG_CHECK_NAME, :P_ENT_NAME, :P_ORG_REGISTER_NO, :P_BUDGET_TYPE_ID, :P_BUDGET_SHORT_NAME, :P_SALBAR_ANGILAL, :P_DEPARTMENT_NAME, :P_CHECK_DEPARTMENT_NAME, :P_AUDIT_DEPARTMENT_NAME, :P_CREATED_BY); END;`;

      let data = [];
      let log = [];
      function getData(req) {
        if (req.body.data?.length > 0) {
          req.body.data?.forEach((element) => {
            data.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        if (req.body.log?.length > 0) {
          req.body.log?.forEach((element) => {
            log.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_BM2_ID: CheckNullInt(element.BM2_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_AUDIT_TYPE_NAME: element.AUDIT_TYPE_NAME,
              P_AUDIT_NAME: element.AUDIT_NAME,
              P_AUDIT_CODE: element.AUDIT_CODE,
              P_FORM_TYPE_ID: CheckNullInt(element.FORM_TYPE_ID),
              P_AUDIT_TYPE: element.AUDIT_TYPE,
              P_AUDIT_ORG_TYPE: CheckNullInt(element.AUDIT_ORG_TYPE),
              P_AUDIT_ORG_CHECK_NAME: element.AUDIT_ORG_CHECK_NAME,
              P_ENT_NAME: element.ENT_NAME,
              P_ORG_REGISTER_NO: element.ORG_REGISTER_NO,
              P_BUDGET_TYPE_ID: CheckNullInt(element.BUDGET_TYPE_ID),
              P_BUDGET_SHORT_NAME: element.BUDGET_SHORT_NAME,
              P_SALBAR_ANGILAL: element.SALBAR_ANGILAL,
              P_DEPARTMENT_NAME: element.DEPARTMENT_NAME,
              P_CHECK_DEPARTMENT_NAME: element.CHECK_DEPARTMENT_NAME,
              P_AUDIT_DEPARTMENT_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        return { data };
      }

      getData(req);

      const result = await OracleDB.multipleExecute(queryBM2, data);
      const resultLog = await OracleDB.multipleExecute(queryBM2log, log);
      return res.send({
        message: "Хадгаллаа.",
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM3List(req, res) {
    try {
      let paramID = {};
      paramID.P_ID = parseInt(req.body.ID, 10);

      const resultFindID = await OracleDB.simpleExecute(FindIDs, paramID);

      let params = {};
      params.P_PERIOD_ID = resultFindID.rows[0]?.PERIOD_ID;
      params.P_DEPARTMENT_ID = resultFindID.rows[0]?.DEPARTMENT_ID;

      let ListQuery = `SELECT 
      FA.ID AUDIT_ID,
      RAT.AUDIT_TYPE_ID,
      RAT.AUDIT_TYPE_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ||' - '|| RAT.AUDIT_TYPE_NAME AUDIT_NAME,
      FA.AUDIT_CODE,
      RFT.FORM_TYPE_ID,
      RFT.FORM_TYPE_NAME AUDIT_TYPE,
      FA.AUDIT_ORG_TYPE,
      RAOT.AUDIT_ORG_CHECK_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ENT_NAME,
      AO.ORG_REGISTER_NO,
      RBT.BUDGET_TYPE_ID,
      RBT.BUDGET_SHORT_NAME,
      RD.DEPARTMENT_NAME AS CHECK_DEPARTMENT_NAME,
      RD1.DEPARTMENT_NAME AS AUDIT_DEPARTMENT_NAME,
      A.IS_ZALRUULAH,
      A.IS_ZALRUULAH_NAME,
      A.ALD_SHORT_DESC,
      A.AMOUNT,
      A.IS_SUB_ERROR_CONFLICT,
      A.IS_SUB_ERROR_CONFLICT_NAME,
      A.UR_UGUUJ, A.UR_UGUUJ_NAME,
      A.UR_UGUUJ_TYPE, A.UR_UGUUJ_TYPE_NAME
      FROM FAS_ADMIN.FAS_AUDIT FA
      INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID
      INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
      LEFT JOIN FAS_ADMIN.ENTITY_NAME EN ON FA.ENT_ID = EN.ENT_ID 
      INNER JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_TYPE RAT ON FA.AUDIT_TYPE = RAT.AUDIT_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_FORM_TYPE RFT ON FA.AUDIT_FORM_TYPE = RFT.FORM_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_ORG_TYPE RAOT ON FA.AUDIT_ORG_TYPE = RAOT.ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD ON FA.USER_DEPARTMENT_ID = RD.DEPARTMENT_ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD1 ON FA.AUDIT_CHECK_DEP_ID = RD1.DEPARTMENT_ID
      INNER JOIN ((
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        NULL IS_ZALRUULAH, NULL IS_ZALRUULAH_NAME,
        NULL IS_SUB_ERROR_CONFLICT, NULL IS_SUB_ERROR_CONFLICT_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME
        FROM FAS_ADMIN.FAS_DOC_5_5_SAMPLE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_5
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION != 341 AND A.IS_ERROR_CONFLICT = 285
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        NULL IS_ZALRUULAH, NULL IS_ZALRUULAH_NAME,
        NULL IS_SUB_ERROR_CONFLICT, NULL IS_SUB_ERROR_CONFLICT_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL AND A.IS_ERROR_CONFLICT = 285
        ) 
        UNION
        (
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        NULL IS_ZALRUULAH, NULL IS_ZALRUULAH_NAME,
        NULL IS_SUB_ERROR_CONFLICT, NULL IS_SUB_ERROR_CONFLICT_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL AND A.IS_ERROR_CONFLICT = 285
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        B.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        A.IS_ZALRUULAH, V6.IND_VALUE_NAME IS_ZALRUULAH_NAME,
        D.IS_SUB_ERROR_CONFLICT, V7.IND_VALUE_NAME IS_SUB_ERROR_CONFLICT_NAME,
        B.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME
        FROM FAS_ADMIN.FAS_DOC_5_1 A
        INNER JOIN FAS_ADMIN.FAS_DOC_5_5 B ON A.ID = B.ID_5_1
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_2 D ON A.ID = D.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON B.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V6 ON A.IS_ZALRUULAH = V6.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V7 ON D.IS_SUB_ERROR_CONFLICT = V7.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON B.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        WHERE A.IS_ACTIVE = 1 AND B.SOLUTION != 341 AND A.IS_ERROR_CONFLICT = 285
        )) A ON FA.ID = A.FAS_AUDIT_ID
      WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1
      AND FA.AUDIT_CHECK_DEP_ID = :P_DEPARTMENT_ID AND FA.PERIOD_ID = :P_PERIOD_ID`;

      //ListQuery += `\n ORDER BY BM1.ID`;

      const result = await OracleDB.simpleExecute(ListQuery, params);
      const resultRole = await OracleDB.simpleExecute(ListTeamRole, paramID);
      const resultStatus = await OracleDB.simpleExecute(AuditStatus, paramID);

      return res.send({
        data: result.rows,
        role: resultRole.rows,
        status:
          resultStatus.rows[0] !== undefined ? resultStatus.rows[0] : null,
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM3IU(req, res) {
    try {
      const queryBM3 = `BEGIN AUD_STAT.NEW_BM3_I_U(:P_ID, :P_AUDIT_ID, :P_AUDIT_TYPE_ID, :P_CREATED_BY); END;`;
      const queryBM3log = `BEGIN AUD_STAT.NEW_BM3_LOG_I_U(:P_ID, :P_AUDIT_ID, :P_BM3_ID, :P_AUDIT_TYPE_ID, :P_AUDIT_TYPE_NAME, :P_AUDIT_NAME, :P_AUDIT_CODE, :P_FORM_TYPE_ID, :P_AUDIT_TYPE, :P_AUDIT_ORG_TYPE, :P_AUDIT_ORG_CHECK_NAME, :P_ENT_NAME, :P_ORG_REGISTER_NO, :P_BUDGET_TYPE_ID, :P_BUDGET_SHORT_NAME, :P_SALBAR_ANGILAL, :P_CHECK_DEPARTMENT_NAME, :P_AUDIT_DEPARTMENT_NAME, :P_IS_ZALRUULAH, :P_IS_ZALRUULAH_NAME, :P_ALD_SHORT_DESC, :P_AMOUNT, :P_IS_SUB_ERROR_CONFLICT, :P_IS_SUB_ERROR_CONFLICT_NAME, :P_UR_UGUUJ, :P_UR_UGUUJ_NAME, :P_UR_UGUUJ_TYPE, :P_UR_UGUUJ_TYPE_NAME, :P_CREATED_BY); END;`;

      let data = [];
      let log = [];
      function getData(req) {
        if (req.body.data?.length > 0) {
          req.body.data?.forEach((element) => {
            data.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        if (req.body.log?.length > 0) {
          req.body.log?.forEach((element) => {
            log.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_BM3_ID: CheckNullInt(element.BM3_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_AUDIT_TYPE_NAME: element.AUDIT_TYPE_NAME,
              P_AUDIT_NAME: element.AUDIT_NAME,
              P_AUDIT_CODE: element.AUDIT_CODE,
              P_FORM_TYPE_ID: CheckNullInt(element.FORM_TYPE_ID),
              P_AUDIT_TYPE: element.AUDIT_TYPE,
              P_AUDIT_ORG_TYPE: CheckNullInt(element.AUDIT_ORG_TYPE),
              P_AUDIT_ORG_CHECK_NAME: element.AUDIT_ORG_CHECK_NAME,
              P_ENT_NAME: element.ENT_NAME,
              P_ORG_REGISTER_NO: element.ORG_REGISTER_NO,
              P_BUDGET_TYPE_ID: CheckNullInt(element.BUDGET_TYPE_ID),
              P_BUDGET_SHORT_NAME: element.BUDGET_SHORT_NAME,
              P_SALBAR_ANGILAL: element.SALBAR_ANGILAL,
              P_CHECK_DEPARTMENT_NAME: element.CHECK_DEPARTMENT_NAME,
              P_AUDIT_DEPARTMENT_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_IS_ZALRUULAH: CheckNullInt(element.IS_ZALRUULAH),
              P_IS_ZALRUULAH_NAME: element.IS_ZALRUULAH_NAME,
              P_ALD_SHORT_DESC: element.ALD_SHORT_DESC,
              P_AMOUNT: CheckNullFloat(element.AMOUNT),
              P_IS_SUB_ERROR_CONFLICT: CheckNullInt(
                element.IS_SUB_ERROR_CONFLICT
              ),
              P_IS_SUB_ERROR_CONFLICT_NAME: element.IS_SUB_ERROR_CONFLICT_NAME,
              P_UR_UGUUJ: CheckNullInt(element.UR_UGUUJ),
              P_UR_UGUUJ_NAME: element.UR_UGUUJ_NAME,
              P_UR_UGUUJ_TYPE: CheckNullInt(element.AUDIT_DEPARTMENT_NAME),
              P_UR_UGUUJ_TYPE_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        return { data };
      }

      getData(req);

      const result = await OracleDB.multipleExecute(queryBM3, data);
      const resultLog = await OracleDB.multipleExecute(queryBM3log, log);
      return res.send({
        message: "Хадгаллаа.",
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM4List(req, res) {
    try {
      let paramID = {};
      paramID.P_ID = parseInt(req.body.ID, 10);

      const resultFindID = await OracleDB.simpleExecute(FindIDs, paramID);

      let params = {};
      params.P_PERIOD_ID = resultFindID.rows[0]?.PERIOD_ID;
      params.P_DEPARTMENT_ID = resultFindID.rows[0]?.DEPARTMENT_ID;

      let ListQuery = `SELECT 
      FA.ID FAS_AUDIT_ID,
      RAT.AUDIT_TYPE_ID,
      RAT.AUDIT_TYPE_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ||' - '|| RAT.AUDIT_TYPE_NAME AUDIT_NAME,
      FA.AUDIT_CODE,
      RFT.FORM_TYPE_ID,
      RFT.FORM_TYPE_NAME AUDIT_TYPE,
      FA.AUDIT_ORG_TYPE,
      RAOT.AUDIT_ORG_CHECK_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ENT_NAME,
      AO.ORG_REGISTER_NO,
      RBT.BUDGET_TYPE_ID,
      RBT.BUDGET_SHORT_NAME,
      RD.DEPARTMENT_NAME AS CHECK_DEPARTMENT_NAME,
      RD1.DEPARTMENT_NAME AS AUDIT_DEPARTMENT_NAME,
      A.ID, A.ALD_SHORT_DESC,
        A.SOLUTION, A.SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, A.IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, A.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, A.UR_UGUUJ_NAME,
        A.UR_UGUUJ_TYPE, A.UR_UGUUJ_TYPE_NAME,
        A.AKT_DATE, A.AKT_NO, A.SHORT_DESC,
        A.USER_ID, A.AUDITOR_NAME, A.AUDITOR_CODE, A.MO_DATE, A.MO_AMOUNT,
        A.TUL_AMOUNT, A.TOD_AMOUNT
      FROM FAS_ADMIN.FAS_AUDIT FA
      INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID
      INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
      LEFT JOIN FAS_ADMIN.ENTITY_NAME EN ON FA.ENT_ID = EN.ENT_ID 
      INNER JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_TYPE RAT ON FA.AUDIT_TYPE = RAT.AUDIT_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_FORM_TYPE RFT ON FA.AUDIT_FORM_TYPE = RFT.FORM_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_ORG_TYPE RAOT ON FA.AUDIT_ORG_TYPE = RAOT.ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD ON FA.USER_DEPARTMENT_ID = RD.DEPARTMENT_ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD1 ON FA.AUDIT_CHECK_DEP_ID = RD1.DEPARTMENT_ID
      INNER JOIN ((
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_5_SAMPLE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_5
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION != 341
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL
        ) 
        UNION
        (
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        B.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        B.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        B.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1 A
        INNER JOIN FAS_ADMIN.FAS_DOC_5_5 B ON A.ID = B.ID_5_1
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_2 D ON A.ID = D.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON B.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON B.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON B.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND B.SOLUTION != 341
        )) A ON FA.ID = A.FAS_AUDIT_ID
      WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1 AND A.SOLUTION = 315
      AND FA.AUDIT_CHECK_DEP_ID = :P_DEPARTMENT_ID AND FA.PERIOD_ID = :P_PERIOD_ID`;

      //ListQuery += `\n ORDER BY BM1.ID`;

      const result = await OracleDB.simpleExecute(ListQuery, params);
      const resultRole = await OracleDB.simpleExecute(ListTeamRole, paramID);
      const resultStatus = await OracleDB.simpleExecute(AuditStatus, paramID);

      return res.send({
        data: result.rows,
        role: resultRole.rows,
        status:
          resultStatus.rows[0] !== undefined ? resultStatus.rows[0] : null,
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM4IU(req, res) {
    try {
      const queryBM4 = `BEGIN AUD_STAT.NEW_BM4_I_U(:P_ID, :P_AUDIT_ID, :P_AUDIT_TYPE_ID, :P_CREATED_BY); END;`;
      //const queryBM4log = `BEGIN AUD_STAT.NEW_BM4_LOG_I_U(:P_ID, :P_AUDIT_ID, :P_BM4_ID, :P_AUDIT_TYPE_ID, :P_AUDIT_TYPE_NAME, :P_AUDIT_NAME, :P_AUDIT_CODE, :P_FORM_TYPE_ID, :P_AUDIT_TYPE, :P_AUDIT_ORG_TYPE, :P_AUDIT_ORG_CHECK_NAME, :P_ENT_NAME, :P_ORG_REGISTER_NO, :P_BUDGET_TYPE_ID, :P_BUDGET_SHORT_NAME, :P_SALBAR_ANGILAL, :P_CHECK_DEPARTMENT_NAME, :P_AUDIT_DEPARTMENT_NAME, :P_IS_ZALRUULAH, :P_IS_ZALRUULAH_NAME, :P_ALD_SHORT_DESC, :P_AMOUNT, :P_IS_SUB_ERROR_CONFLICT, :P_IS_SUB_ERROR_CONFLICT_NAME, :P_UR_UGUUJ, :P_UR_UGUUJ_NAME, :P_UR_UGUUJ_TYPE, :P_UR_UGUUJ_TYPE_NAME, :P_CREATED_BY); END;`;

      let data = [];
      let log = [];
      function getData(req) {
        if (req.body.data?.length > 0) {
          req.body.data?.forEach((element) => {
            data.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        if (req.body.log?.length > 0) {
          req.body.log?.forEach((element) => {
            log.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_BM3_ID: CheckNullInt(element.BM3_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_AUDIT_TYPE_NAME: element.AUDIT_TYPE_NAME,
              P_AUDIT_NAME: element.AUDIT_NAME,
              P_AUDIT_CODE: element.AUDIT_CODE,
              P_FORM_TYPE_ID: CheckNullInt(element.FORM_TYPE_ID),
              P_AUDIT_TYPE: element.AUDIT_TYPE,
              P_AUDIT_ORG_TYPE: CheckNullInt(element.AUDIT_ORG_TYPE),
              P_AUDIT_ORG_CHECK_NAME: element.AUDIT_ORG_CHECK_NAME,
              P_ENT_NAME: element.ENT_NAME,
              P_ORG_REGISTER_NO: element.ORG_REGISTER_NO,
              P_BUDGET_TYPE_ID: CheckNullInt(element.BUDGET_TYPE_ID),
              P_BUDGET_SHORT_NAME: element.BUDGET_SHORT_NAME,
              P_SALBAR_ANGILAL: element.SALBAR_ANGILAL,
              P_CHECK_DEPARTMENT_NAME: element.CHECK_DEPARTMENT_NAME,
              P_AUDIT_DEPARTMENT_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_IS_ZALRUULAH: CheckNullInt(element.IS_ZALRUULAH),
              P_IS_ZALRUULAH_NAME: element.IS_ZALRUULAH_NAME,
              P_ALD_SHORT_DESC: element.ALD_SHORT_DESC,
              P_AMOUNT: CheckNullFloat(element.AMOUNT),
              P_IS_SUB_ERROR_CONFLICT: CheckNullInt(
                element.IS_SUB_ERROR_CONFLICT
              ),
              P_IS_SUB_ERROR_CONFLICT_NAME: element.IS_SUB_ERROR_CONFLICT_NAME,
              P_UR_UGUUJ: CheckNullInt(element.UR_UGUUJ),
              P_UR_UGUUJ_NAME: element.UR_UGUUJ_NAME,
              P_UR_UGUUJ_TYPE: CheckNullInt(element.AUDIT_DEPARTMENT_NAME),
              P_UR_UGUUJ_TYPE_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        return { data };
      }

      getData(req);

      const result = await OracleDB.multipleExecute(queryBM4, data);
      //const resultLog = await OracleDB.multipleExecute(queryBM4log, log);
      return res.send({
        message: "Хадгаллаа.",
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM5List(req, res) {
    try {
      let paramID = {};
      paramID.P_ID = parseInt(req.body.ID, 10);

      const resultFindID = await OracleDB.simpleExecute(FindIDs, paramID);

      let params = {};
      params.P_PERIOD_ID = resultFindID.rows[0]?.PERIOD_ID;
      params.P_DEPARTMENT_ID = resultFindID.rows[0]?.DEPARTMENT_ID;

      let ListQuery = `SELECT 
      FA.ID FAS_AUDIT_ID,
      RAT.AUDIT_TYPE_ID,
      RAT.AUDIT_TYPE_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ||' - '|| RAT.AUDIT_TYPE_NAME AUDIT_NAME,
      FA.AUDIT_CODE,
      RFT.FORM_TYPE_ID,
      RFT.FORM_TYPE_NAME AUDIT_TYPE,
      FA.AUDIT_ORG_TYPE,
      RAOT.AUDIT_ORG_CHECK_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ENT_NAME,
      AO.ORG_REGISTER_NO,
      RBT.BUDGET_TYPE_ID,
      RBT.BUDGET_SHORT_NAME,
      RD.DEPARTMENT_NAME AS CHECK_DEPARTMENT_NAME,
      RD1.DEPARTMENT_NAME AS AUDIT_DEPARTMENT_NAME,
      A.ID, A.ALD_SHORT_DESC,
        A.SOLUTION, A.SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, A.IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, A.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, A.UR_UGUUJ_NAME,
        A.UR_UGUUJ_TYPE, A.UR_UGUUJ_TYPE_NAME,
        A.AKT_DATE, A.AKT_NO, A.SHORT_DESC,
        A.USER_ID, A.AUDITOR_NAME, A.AUDITOR_CODE, A.MO_DATE, A.MO_AMOUNT,
        A.TUL_AMOUNT, A.TOD_AMOUNT
      FROM FAS_ADMIN.FAS_AUDIT FA
      INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID
      INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
      LEFT JOIN FAS_ADMIN.ENTITY_NAME EN ON FA.ENT_ID = EN.ENT_ID 
      INNER JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_TYPE RAT ON FA.AUDIT_TYPE = RAT.AUDIT_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_FORM_TYPE RFT ON FA.AUDIT_FORM_TYPE = RFT.FORM_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_ORG_TYPE RAOT ON FA.AUDIT_ORG_TYPE = RAOT.ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD ON FA.USER_DEPARTMENT_ID = RD.DEPARTMENT_ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD1 ON FA.AUDIT_CHECK_DEP_ID = RD1.DEPARTMENT_ID
      INNER JOIN ((
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_5_SAMPLE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_5
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION != 341
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL
        ) 
        UNION
        (
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        B.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        B.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        B.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1 A
        INNER JOIN FAS_ADMIN.FAS_DOC_5_5 B ON A.ID = B.ID_5_1
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_2 D ON A.ID = D.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON B.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON B.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON B.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND B.SOLUTION != 341
        )) A ON FA.ID = A.FAS_AUDIT_ID
      WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1 AND A.SOLUTION = 316
      AND FA.AUDIT_CHECK_DEP_ID = :P_DEPARTMENT_ID AND FA.PERIOD_ID = :P_PERIOD_ID`;

      //ListQuery += `\n ORDER BY BM1.ID`;

      const result = await OracleDB.simpleExecute(ListQuery, params);
      const resultRole = await OracleDB.simpleExecute(ListTeamRole, paramID);
      const resultStatus = await OracleDB.simpleExecute(AuditStatus, paramID);

      return res.send({
        data: result.rows,
        role: resultRole.rows,
        status:
          resultStatus.rows[0] !== undefined ? resultStatus.rows[0] : null,
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM5IU(req, res) {
    try {
      const queryBM5 = `BEGIN AUD_STAT.NEW_BM5_I_U(:P_ID, :P_AUDIT_ID, :P_AUDIT_TYPE_ID, :P_CREATED_BY); END;`;
      //const queryBM5log = `BEGIN AUD_STAT.NEW_BM5_LOG_I_U(:P_ID, :P_AUDIT_ID, :P_BM5_ID, :P_AUDIT_TYPE_ID, :P_AUDIT_TYPE_NAME, :P_AUDIT_NAME, :P_AUDIT_CODE, :P_FORM_TYPE_ID, :P_AUDIT_TYPE, :P_AUDIT_ORG_TYPE, :P_AUDIT_ORG_CHECK_NAME, :P_ENT_NAME, :P_ORG_REGISTER_NO, :P_BUDGET_TYPE_ID, :P_BUDGET_SHORT_NAME, :P_SALBAR_ANGILAL, :P_CHECK_DEPARTMENT_NAME, :P_AUDIT_DEPARTMENT_NAME, :P_IS_ZALRUULAH, :P_IS_ZALRUULAH_NAME, :P_ALD_SHORT_DESC, :P_AMOUNT, :P_IS_SUB_ERROR_CONFLICT, :P_IS_SUB_ERROR_CONFLICT_NAME, :P_UR_UGUUJ, :P_UR_UGUUJ_NAME, :P_UR_UGUUJ_TYPE, :P_UR_UGUUJ_TYPE_NAME, :P_CREATED_BY); END;`;

      let data = [];
      let log = [];
      function getData(req) {
        if (req.body.data?.length > 0) {
          req.body.data?.forEach((element) => {
            data.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        if (req.body.log?.length > 0) {
          req.body.log?.forEach((element) => {
            log.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_BM3_ID: CheckNullInt(element.BM3_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_AUDIT_TYPE_NAME: element.AUDIT_TYPE_NAME,
              P_AUDIT_NAME: element.AUDIT_NAME,
              P_AUDIT_CODE: element.AUDIT_CODE,
              P_FORM_TYPE_ID: CheckNullInt(element.FORM_TYPE_ID),
              P_AUDIT_TYPE: element.AUDIT_TYPE,
              P_AUDIT_ORG_TYPE: CheckNullInt(element.AUDIT_ORG_TYPE),
              P_AUDIT_ORG_CHECK_NAME: element.AUDIT_ORG_CHECK_NAME,
              P_ENT_NAME: element.ENT_NAME,
              P_ORG_REGISTER_NO: element.ORG_REGISTER_NO,
              P_BUDGET_TYPE_ID: CheckNullInt(element.BUDGET_TYPE_ID),
              P_BUDGET_SHORT_NAME: element.BUDGET_SHORT_NAME,
              P_SALBAR_ANGILAL: element.SALBAR_ANGILAL,
              P_CHECK_DEPARTMENT_NAME: element.CHECK_DEPARTMENT_NAME,
              P_AUDIT_DEPARTMENT_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_IS_ZALRUULAH: CheckNullInt(element.IS_ZALRUULAH),
              P_IS_ZALRUULAH_NAME: element.IS_ZALRUULAH_NAME,
              P_ALD_SHORT_DESC: element.ALD_SHORT_DESC,
              P_AMOUNT: CheckNullFloat(element.AMOUNT),
              P_IS_SUB_ERROR_CONFLICT: CheckNullInt(
                element.IS_SUB_ERROR_CONFLICT
              ),
              P_IS_SUB_ERROR_CONFLICT_NAME: element.IS_SUB_ERROR_CONFLICT_NAME,
              P_UR_UGUUJ: CheckNullInt(element.UR_UGUUJ),
              P_UR_UGUUJ_NAME: element.UR_UGUUJ_NAME,
              P_UR_UGUUJ_TYPE: CheckNullInt(element.AUDIT_DEPARTMENT_NAME),
              P_UR_UGUUJ_TYPE_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        return { data };
      }

      getData(req);

      const result = await OracleDB.multipleExecute(queryBM5, data);
      // const resultLog = await OracleDB.multipleExecute(queryBM5log, log);
      return res.send({
        message: "Хадгаллаа.",
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM6List(req, res) {
    try {
      let paramID = {};
      paramID.P_ID = parseInt(req.body.ID, 10);

      const resultFindID = await OracleDB.simpleExecute(FindIDs, paramID);

      let params = {};
      params.P_PERIOD_ID = resultFindID.rows[0]?.PERIOD_ID;
      params.P_DEPARTMENT_ID = resultFindID.rows[0]?.DEPARTMENT_ID;

      let ListQuery = `SELECT 
      FA.ID FAS_AUDIT_ID,
      RAT.AUDIT_TYPE_ID,
      RAT.AUDIT_TYPE_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ||' - '|| RAT.AUDIT_TYPE_NAME AUDIT_NAME,
      FA.AUDIT_CODE,
      RFT.FORM_TYPE_ID,
      RFT.FORM_TYPE_NAME AUDIT_TYPE,
      FA.AUDIT_ORG_TYPE,
      RAOT.AUDIT_ORG_CHECK_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ENT_NAME,
      AO.ORG_REGISTER_NO,
      RBT.BUDGET_TYPE_ID,
      RBT.BUDGET_SHORT_NAME,
      RD.DEPARTMENT_NAME AS CHECK_DEPARTMENT_NAME,
      RD1.DEPARTMENT_NAME AS AUDIT_DEPARTMENT_NAME,
      A.ID, A.ALD_SHORT_DESC,
        A.SOLUTION, A.SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, A.IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, A.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, A.UR_UGUUJ_NAME,
        A.UR_UGUUJ_TYPE, A.UR_UGUUJ_TYPE_NAME,
        A.AKT_DATE, A.AKT_NO, A.SHORT_DESC,
        A.USER_ID, A.AUDITOR_NAME, A.AUDITOR_CODE, A.MO_DATE, A.MO_AMOUNT,
        A.TUL_AMOUNT, A.TOD_AMOUNT
      FROM FAS_ADMIN.FAS_AUDIT FA
      INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID
      INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
      LEFT JOIN FAS_ADMIN.ENTITY_NAME EN ON FA.ENT_ID = EN.ENT_ID 
      INNER JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_TYPE RAT ON FA.AUDIT_TYPE = RAT.AUDIT_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_FORM_TYPE RFT ON FA.AUDIT_FORM_TYPE = RFT.FORM_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_ORG_TYPE RAOT ON FA.AUDIT_ORG_TYPE = RAOT.ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD ON FA.USER_DEPARTMENT_ID = RD.DEPARTMENT_ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD1 ON FA.AUDIT_CHECK_DEP_ID = RD1.DEPARTMENT_ID
      INNER JOIN ((
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_5_SAMPLE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_5
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION != 341
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL
        ) 
        UNION
        (
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        B.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        B.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        B.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1 A
        INNER JOIN FAS_ADMIN.FAS_DOC_5_5 B ON A.ID = B.ID_5_1
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_2 D ON A.ID = D.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON B.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON B.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON B.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND B.SOLUTION != 341
        )) A ON FA.ID = A.FAS_AUDIT_ID
      WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1 AND A.SOLUTION = 318
      AND FA.AUDIT_CHECK_DEP_ID = :P_DEPARTMENT_ID AND FA.PERIOD_ID = :P_PERIOD_ID`;

      //ListQuery += `\n ORDER BY BM1.ID`;

      const result = await OracleDB.simpleExecute(ListQuery, params);
      const resultRole = await OracleDB.simpleExecute(ListTeamRole, paramID);
      const resultStatus = await OracleDB.simpleExecute(AuditStatus, paramID);

      return res.send({
        data: result.rows,
        role: resultRole.rows,
        status:
          resultStatus.rows[0] !== undefined ? resultStatus.rows[0] : null,
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM6IU(req, res) {
    try {
      const queryBM6 = `BEGIN AUD_STAT.NEW_BM6_I_U(:P_ID, :P_AUDIT_ID, :P_AUDIT_TYPE_ID, :P_CREATED_BY); END;`;
      //const queryBM6log = `BEGIN AUD_STAT.NEW_BM6_LOG_I_U(:P_ID, :P_AUDIT_ID, :P_BM6_ID, :P_AUDIT_TYPE_ID, :P_AUDIT_TYPE_NAME, :P_AUDIT_NAME, :P_AUDIT_CODE, :P_FORM_TYPE_ID, :P_AUDIT_TYPE, :P_AUDIT_ORG_TYPE, :P_AUDIT_ORG_CHECK_NAME, :P_ENT_NAME, :P_ORG_REGISTER_NO, :P_BUDGET_TYPE_ID, :P_BUDGET_SHORT_NAME, :P_SALBAR_ANGILAL, :P_CHECK_DEPARTMENT_NAME, :P_AUDIT_DEPARTMENT_NAME, :P_IS_ZALRUULAH, :P_IS_ZALRUULAH_NAME, :P_ALD_SHORT_DESC, :P_AMOUNT, :P_IS_SUB_ERROR_CONFLICT, :P_IS_SUB_ERROR_CONFLICT_NAME, :P_UR_UGUUJ, :P_UR_UGUUJ_NAME, :P_UR_UGUUJ_TYPE, :P_UR_UGUUJ_TYPE_NAME, :P_CREATED_BY); END;`;

      let data = [];
      let log = [];
      function getData(req) {
        if (req.body.data?.length > 0) {
          req.body.data?.forEach((element) => {
            data.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        if (req.body.log?.length > 0) {
          req.body.log?.forEach((element) => {
            log.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_BM3_ID: CheckNullInt(element.BM3_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_AUDIT_TYPE_NAME: element.AUDIT_TYPE_NAME,
              P_AUDIT_NAME: element.AUDIT_NAME,
              P_AUDIT_CODE: element.AUDIT_CODE,
              P_FORM_TYPE_ID: CheckNullInt(element.FORM_TYPE_ID),
              P_AUDIT_TYPE: element.AUDIT_TYPE,
              P_AUDIT_ORG_TYPE: CheckNullInt(element.AUDIT_ORG_TYPE),
              P_AUDIT_ORG_CHECK_NAME: element.AUDIT_ORG_CHECK_NAME,
              P_ENT_NAME: element.ENT_NAME,
              P_ORG_REGISTER_NO: element.ORG_REGISTER_NO,
              P_BUDGET_TYPE_ID: CheckNullInt(element.BUDGET_TYPE_ID),
              P_BUDGET_SHORT_NAME: element.BUDGET_SHORT_NAME,
              P_SALBAR_ANGILAL: element.SALBAR_ANGILAL,
              P_CHECK_DEPARTMENT_NAME: element.CHECK_DEPARTMENT_NAME,
              P_AUDIT_DEPARTMENT_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_IS_ZALRUULAH: CheckNullInt(element.IS_ZALRUULAH),
              P_IS_ZALRUULAH_NAME: element.IS_ZALRUULAH_NAME,
              P_ALD_SHORT_DESC: element.ALD_SHORT_DESC,
              P_AMOUNT: CheckNullFloat(element.AMOUNT),
              P_IS_SUB_ERROR_CONFLICT: CheckNullInt(
                element.IS_SUB_ERROR_CONFLICT
              ),
              P_IS_SUB_ERROR_CONFLICT_NAME: element.IS_SUB_ERROR_CONFLICT_NAME,
              P_UR_UGUUJ: CheckNullInt(element.UR_UGUUJ),
              P_UR_UGUUJ_NAME: element.UR_UGUUJ_NAME,
              P_UR_UGUUJ_TYPE: CheckNullInt(element.AUDIT_DEPARTMENT_NAME),
              P_UR_UGUUJ_TYPE_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        return { data };
      }

      getData(req);

      const result = await OracleDB.multipleExecute(queryBM6, data);
      //const resultLog = await OracleDB.multipleExecute(queryBM6log, log);
      return res.send({
        message: "Хадгаллаа.",
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM7List(req, res) {
    try {
      let paramID = {};
      paramID.P_ID = parseInt(req.body.ID, 10);

      const resultFindID = await OracleDB.simpleExecute(FindIDs, paramID);

      let params = {};
      params.P_PERIOD_ID = resultFindID.rows[0]?.PERIOD_ID;
      params.P_DEPARTMENT_ID = resultFindID.rows[0]?.DEPARTMENT_ID;

      let ListQuery = `SELECT 
      FA.ID FAS_AUDIT_ID,
      RAT.AUDIT_TYPE_ID,
      RAT.AUDIT_TYPE_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ||' - '|| RAT.AUDIT_TYPE_NAME AUDIT_NAME,
      FA.AUDIT_CODE,
      RFT.FORM_TYPE_ID,
      RFT.FORM_TYPE_NAME AUDIT_TYPE,
      FA.AUDIT_ORG_TYPE,
      RAOT.AUDIT_ORG_CHECK_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ENT_NAME,
      AO.ORG_REGISTER_NO,
      RBT.BUDGET_TYPE_ID,
      RBT.BUDGET_SHORT_NAME,
      RD.DEPARTMENT_NAME AS CHECK_DEPARTMENT_NAME,
      RD1.DEPARTMENT_NAME AS AUDIT_DEPARTMENT_NAME,
      A.ID, A.ALD_SHORT_DESC,
        A.SOLUTION, A.SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, A.IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, A.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, A.UR_UGUUJ_NAME,
        A.UR_UGUUJ_TYPE, A.UR_UGUUJ_TYPE_NAME,
        A.AKT_DATE, A.AKT_NO, A.SHORT_DESC,
        A.USER_ID, A.AUDITOR_NAME, A.AUDITOR_CODE, A.MO_DATE, A.MO_AMOUNT,
        A.TUL_AMOUNT, A.TOD_AMOUNT
      FROM FAS_ADMIN.FAS_AUDIT FA
      INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID
      INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
      LEFT JOIN FAS_ADMIN.ENTITY_NAME EN ON FA.ENT_ID = EN.ENT_ID 
      INNER JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_TYPE RAT ON FA.AUDIT_TYPE = RAT.AUDIT_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_FORM_TYPE RFT ON FA.AUDIT_FORM_TYPE = RFT.FORM_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_ORG_TYPE RAOT ON FA.AUDIT_ORG_TYPE = RAOT.ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD ON FA.USER_DEPARTMENT_ID = RD.DEPARTMENT_ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD1 ON FA.AUDIT_CHECK_DEP_ID = RD1.DEPARTMENT_ID
      INNER JOIN ((
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_5_SAMPLE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_5
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION != 341
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL
        ) 
        UNION
        (
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        B.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        B.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        B.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1 A
        INNER JOIN FAS_ADMIN.FAS_DOC_5_5 B ON A.ID = B.ID_5_1
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_2 D ON A.ID = D.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON B.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON B.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON B.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND B.SOLUTION != 341
        )) A ON FA.ID = A.FAS_AUDIT_ID
      WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1 AND A.SOLUTION = 317
      AND FA.AUDIT_CHECK_DEP_ID = :P_DEPARTMENT_ID AND FA.PERIOD_ID = :P_PERIOD_ID`;

      //ListQuery += `\n ORDER BY BM1.ID`;

      const result = await OracleDB.simpleExecute(ListQuery, params);
      const resultRole = await OracleDB.simpleExecute(ListTeamRole, paramID);
      const resultStatus = await OracleDB.simpleExecute(AuditStatus, paramID);

      return res.send({
        data: result.rows,
        role: resultRole.rows,
        status:
          resultStatus.rows[0] !== undefined ? resultStatus.rows[0] : null,
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM7IU(req, res) {
    try {
      const queryBM7 = `BEGIN AUD_STAT.NEW_BM7_I_U(:P_ID, :P_AUDIT_ID, :P_AUDIT_TYPE_ID, :P_CREATED_BY); END;`;
      //const queryBM7log = `BEGIN AUD_STAT.NEW_BM7_LOG_I_U(:P_ID, :P_AUDIT_ID, :P_BM7_ID, :P_AUDIT_TYPE_ID, :P_AUDIT_TYPE_NAME, :P_AUDIT_NAME, :P_AUDIT_CODE, :P_FORM_TYPE_ID, :P_AUDIT_TYPE, :P_AUDIT_ORG_TYPE, :P_AUDIT_ORG_CHECK_NAME, :P_ENT_NAME, :P_ORG_REGISTER_NO, :P_BUDGET_TYPE_ID, :P_BUDGET_SHORT_NAME, :P_SALBAR_ANGILAL, :P_CHECK_DEPARTMENT_NAME, :P_AUDIT_DEPARTMENT_NAME, :P_IS_ZALRUULAH, :P_IS_ZALRUULAH_NAME, :P_ALD_SHORT_DESC, :P_AMOUNT, :P_IS_SUB_ERROR_CONFLICT, :P_IS_SUB_ERROR_CONFLICT_NAME, :P_UR_UGUUJ, :P_UR_UGUUJ_NAME, :P_UR_UGUUJ_TYPE, :P_UR_UGUUJ_TYPE_NAME, :P_CREATED_BY); END;`;

      let data = [];
      let log = [];
      function getData(req) {
        if (req.body.data?.length > 0) {
          req.body.data?.forEach((element) => {
            data.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        if (req.body.log?.length > 0) {
          req.body.log?.forEach((element) => {
            log.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_BM3_ID: CheckNullInt(element.BM3_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_AUDIT_TYPE_NAME: element.AUDIT_TYPE_NAME,
              P_AUDIT_NAME: element.AUDIT_NAME,
              P_AUDIT_CODE: element.AUDIT_CODE,
              P_FORM_TYPE_ID: CheckNullInt(element.FORM_TYPE_ID),
              P_AUDIT_TYPE: element.AUDIT_TYPE,
              P_AUDIT_ORG_TYPE: CheckNullInt(element.AUDIT_ORG_TYPE),
              P_AUDIT_ORG_CHECK_NAME: element.AUDIT_ORG_CHECK_NAME,
              P_ENT_NAME: element.ENT_NAME,
              P_ORG_REGISTER_NO: element.ORG_REGISTER_NO,
              P_BUDGET_TYPE_ID: CheckNullInt(element.BUDGET_TYPE_ID),
              P_BUDGET_SHORT_NAME: element.BUDGET_SHORT_NAME,
              P_SALBAR_ANGILAL: element.SALBAR_ANGILAL,
              P_CHECK_DEPARTMENT_NAME: element.CHECK_DEPARTMENT_NAME,
              P_AUDIT_DEPARTMENT_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_IS_ZALRUULAH: CheckNullInt(element.IS_ZALRUULAH),
              P_IS_ZALRUULAH_NAME: element.IS_ZALRUULAH_NAME,
              P_ALD_SHORT_DESC: element.ALD_SHORT_DESC,
              P_AMOUNT: CheckNullFloat(element.AMOUNT),
              P_IS_SUB_ERROR_CONFLICT: CheckNullInt(
                element.IS_SUB_ERROR_CONFLICT
              ),
              P_IS_SUB_ERROR_CONFLICT_NAME: element.IS_SUB_ERROR_CONFLICT_NAME,
              P_UR_UGUUJ: CheckNullInt(element.UR_UGUUJ),
              P_UR_UGUUJ_NAME: element.UR_UGUUJ_NAME,
              P_UR_UGUUJ_TYPE: CheckNullInt(element.AUDIT_DEPARTMENT_NAME),
              P_UR_UGUUJ_TYPE_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        return { data };
      }

      getData(req);

      const result = await OracleDB.multipleExecute(queryBM7, data);
      //const resultLog = await OracleDB.multipleExecute(queryBM7log, log);
      return res.send({
        message: "Хадгаллаа.",
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM8List(req, res) {
    try {
      let paramID = {};
      paramID.P_ID = parseInt(req.body.ID, 10);

      const resultFindID = await OracleDB.simpleExecute(FindIDs, paramID);

      let params = {};
      params.P_PERIOD_ID = resultFindID.rows[0]?.PERIOD_ID;
      params.P_DEPARTMENT_ID = resultFindID.rows[0]?.DEPARTMENT_ID;

      let ListQuery = `SELECT 
      FA.ID FAS_AUDIT_ID,
      RAT.AUDIT_TYPE_ID,
      RAT.AUDIT_TYPE_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ||' - '|| RAT.AUDIT_TYPE_NAME AUDIT_NAME,
      FA.AUDIT_CODE,
      RFT.FORM_TYPE_ID,
      RFT.FORM_TYPE_NAME AUDIT_TYPE,
      FA.AUDIT_ORG_TYPE,
      RAOT.AUDIT_ORG_CHECK_NAME,
      NVL(EN.PERIOD5_NAME, NVL(EN.PERIOD4_NAME, NVL(EN.PERIOD3_NAME, AE.ENT_NAME))) ENT_NAME,
      AO.ORG_REGISTER_NO,
      RBT.BUDGET_TYPE_ID,
      RBT.BUDGET_SHORT_NAME,
      RD.DEPARTMENT_NAME AS CHECK_DEPARTMENT_NAME,
      RD1.DEPARTMENT_NAME AS AUDIT_DEPARTMENT_NAME,
      A.ID, A.ALD_SHORT_DESC,
        A.SOLUTION, A.SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, A.IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, A.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, A.UR_UGUUJ_NAME,
        A.UR_UGUUJ_TYPE, A.UR_UGUUJ_TYPE_NAME,
        A.AKT_DATE, A.AKT_NO, A.SHORT_DESC,
        A.USER_ID, A.AUDITOR_NAME, A.AUDITOR_CODE, A.MO_DATE, A.MO_AMOUNT,
        A.TUL_AMOUNT, A.TOD_AMOUNT
      FROM FAS_ADMIN.FAS_AUDIT FA
      INNER JOIN AUD_ORG.AUDIT_ENTITY AE ON FA.ENT_ID = AE.ENT_ID
      INNER JOIN AUD_ORG.AUDIT_ORGANIZATION AO ON AE.ENT_ORG_ID = AO.ORG_ID
      LEFT JOIN FAS_ADMIN.ENTITY_NAME EN ON FA.ENT_ID = EN.ENT_ID 
      INNER JOIN AUD_ORG.REF_BUDGET_TYPE RBT ON AE.ENT_BUDGET_TYPE = RBT.BUDGET_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_TYPE RAT ON FA.AUDIT_TYPE = RAT.AUDIT_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_FORM_TYPE RFT ON FA.AUDIT_FORM_TYPE = RFT.FORM_TYPE_ID
      INNER JOIN FAS_ADMIN.REF_AUDIT_ORG_TYPE RAOT ON FA.AUDIT_ORG_TYPE = RAOT.ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD ON FA.USER_DEPARTMENT_ID = RD.DEPARTMENT_ID
      INNER JOIN AUD_ORG.REF_DEPARTMENT RD1 ON FA.AUDIT_CHECK_DEP_ID = RD1.DEPARTMENT_ID
      INNER JOIN ((
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_5_SAMPLE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_5
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION != 341
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME,
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6_SAMPLE E ON A.ID = E.ID_5_5 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL
        ) 
        UNION
        (
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        A.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        A.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        A.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1_CLAUSE A
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1_CLAUSE
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 1
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON A.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON A.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON A.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND A.SOLUTION IS NOT NULL
        UNION 
        SELECT A.FAS_AUDIT_ID, C.ID, A.SHORT_DESC ALD_SHORT_DESC,
        B.SOLUTION, V1.IND_VALUE_NAME SOLUTION_NAME, 
        A.AMOUNT, 
        A.IS_ERROR_CONFLICT, V2.IND_VALUE_NAME IS_ERROR_CONFLICT_NAME,
        B.SOLUTION_ERROR, V10.SOLUTION_ERROR_NAME,
        B.UR_UGUUJ, V8.IND_VALUE_NAME UR_UGUUJ_NAME,
        E.UR_UGUUJ_TYPE UR_UGUUJ_TYPE, V9.IND_VALUE_NAME UR_UGUUJ_TYPE_NAME,
        C.AKT_DATE, C.AKT_NO, C.SHORT_DESC,
        SU.USER_ID, SU.USER_NAME AUDITOR_NAME, SU.USER_CODE AUDITOR_CODE, M.MO_DATE, M.AMOUNT MO_AMOUNT,
        M.AMOUNT TUL_AMOUNT, NULL TOD_AMOUNT
        FROM FAS_ADMIN.FAS_DOC_5_1 A
        INNER JOIN FAS_ADMIN.FAS_DOC_5_5 B ON A.ID = B.ID_5_1
        INNER JOIN FAS_ADMIN.FAS_DOC_7_1 C ON A.ID = C.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_2 D ON A.ID = D.ID_5_1
        LEFT JOIN FAS_ADMIN.FAS_DOC_5_6 E ON A.ID = E.ID_5_1 AND E.IS_CLAUSE = 0
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V1 ON B.SOLUTION = V1.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V2 ON A.IS_ERROR_CONFLICT = V2.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V8 ON B.UR_UGUUJ = V8.ID
        LEFT JOIN FAS_ADMIN.REF_DOCUMENT_INDICATOR_VALUE V9 ON E.UR_UGUUJ_TYPE = V9.ID
        LEFT JOIN FAS_ADMIN.REF_SOLUTION_ERROR V10 ON B.SOLUTION_ERROR = V10.ID
        LEFT JOIN FAS_ADMIN.AKT_MONITORING M ON C.ID = M.SEVEN_ONE_ID
        LEFT JOIN AUD_REG.SYSTEM_USER SU ON M.CREATED_BY = SU.USER_ID
        WHERE A.IS_ACTIVE = 1 AND B.SOLUTION != 341
        )) A ON FA.ID = A.FAS_AUDIT_ID
      WHERE FA.IS_ACTIVE = 1 AND AE.IS_ACTIVE = 1 AND A.SOLUTION = 319
      AND FA.AUDIT_CHECK_DEP_ID = :P_DEPARTMENT_ID AND FA.PERIOD_ID = :P_PERIOD_ID`;

      //ListQuery += `\n ORDER BY BM1.ID`;

      const result = await OracleDB.simpleExecute(ListQuery, params);
      const resultRole = await OracleDB.simpleExecute(ListTeamRole, paramID);
      const resultStatus = await OracleDB.simpleExecute(AuditStatus, paramID);

      return res.send({
        data: result.rows,
        role: resultRole.rows,
        status:
          resultStatus.rows[0] !== undefined ? resultStatus.rows[0] : null,
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
  async BM8IU(req, res) {
    try {
      const queryBM8 = `BEGIN AUD_STAT.NEW_BM8_I_U(:P_ID, :P_AUDIT_ID, :P_AUDIT_TYPE_ID, :P_CREATED_BY); END;`;
      //const queryBM8log = `BEGIN AUD_STAT.NEW_BM8_LOG_I_U(:P_ID, :P_AUDIT_ID, :P_BM8_ID, :P_AUDIT_TYPE_ID, :P_AUDIT_TYPE_NAME, :P_AUDIT_NAME, :P_AUDIT_CODE, :P_FORM_TYPE_ID, :P_AUDIT_TYPE, :P_AUDIT_ORG_TYPE, :P_AUDIT_ORG_CHECK_NAME, :P_ENT_NAME, :P_ORG_REGISTER_NO, :P_BUDGET_TYPE_ID, :P_BUDGET_SHORT_NAME, :P_SALBAR_ANGILAL, :P_CHECK_DEPARTMENT_NAME, :P_AUDIT_DEPARTMENT_NAME, :P_IS_ZALRUULAH, :P_IS_ZALRUULAH_NAME, :P_ALD_SHORT_DESC, :P_AMOUNT, :P_IS_SUB_ERROR_CONFLICT, :P_IS_SUB_ERROR_CONFLICT_NAME, :P_UR_UGUUJ, :P_UR_UGUUJ_NAME, :P_UR_UGUUJ_TYPE, :P_UR_UGUUJ_TYPE_NAME, :P_CREATED_BY); END;`;

      let data = [];
      let log = [];
      function getData(req) {
        if (req.body.data?.length > 0) {
          req.body.data?.forEach((element) => {
            data.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        if (req.body.log?.length > 0) {
          req.body.log?.forEach((element) => {
            log.push({
              P_ID: element.ID != null ? parseInt(element.ID) : null,
              P_AUDIT_ID: CheckNullInt(element.AUDIT_ID),
              P_BM3_ID: CheckNullInt(element.BM3_ID),
              P_AUDIT_TYPE_ID: CheckNullInt(element.AUDIT_TYPE_ID),
              P_AUDIT_TYPE_NAME: element.AUDIT_TYPE_NAME,
              P_AUDIT_NAME: element.AUDIT_NAME,
              P_AUDIT_CODE: element.AUDIT_CODE,
              P_FORM_TYPE_ID: CheckNullInt(element.FORM_TYPE_ID),
              P_AUDIT_TYPE: element.AUDIT_TYPE,
              P_AUDIT_ORG_TYPE: CheckNullInt(element.AUDIT_ORG_TYPE),
              P_AUDIT_ORG_CHECK_NAME: element.AUDIT_ORG_CHECK_NAME,
              P_ENT_NAME: element.ENT_NAME,
              P_ORG_REGISTER_NO: element.ORG_REGISTER_NO,
              P_BUDGET_TYPE_ID: CheckNullInt(element.BUDGET_TYPE_ID),
              P_BUDGET_SHORT_NAME: element.BUDGET_SHORT_NAME,
              P_SALBAR_ANGILAL: element.SALBAR_ANGILAL,
              P_CHECK_DEPARTMENT_NAME: element.CHECK_DEPARTMENT_NAME,
              P_AUDIT_DEPARTMENT_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_IS_ZALRUULAH: CheckNullInt(element.IS_ZALRUULAH),
              P_IS_ZALRUULAH_NAME: element.IS_ZALRUULAH_NAME,
              P_ALD_SHORT_DESC: element.ALD_SHORT_DESC,
              P_AMOUNT: CheckNullFloat(element.AMOUNT),
              P_IS_SUB_ERROR_CONFLICT: CheckNullInt(
                element.IS_SUB_ERROR_CONFLICT
              ),
              P_IS_SUB_ERROR_CONFLICT_NAME: element.IS_SUB_ERROR_CONFLICT_NAME,
              P_UR_UGUUJ: CheckNullInt(element.UR_UGUUJ),
              P_UR_UGUUJ_NAME: element.UR_UGUUJ_NAME,
              P_UR_UGUUJ_TYPE: CheckNullInt(element.AUDIT_DEPARTMENT_NAME),
              P_UR_UGUUJ_TYPE_NAME: element.AUDIT_DEPARTMENT_NAME,
              P_CREATED_BY: parseInt(req.body.CREATED_BY),
            });
          });
        }
        return { data };
      }

      getData(req);

      const result = await OracleDB.multipleExecute(queryBM8, data);
      //const resultLog = await OracleDB.multipleExecute(queryBM8log, log);
      return res.send({
        message: "Хадгаллаа.",
      });
    } catch (err) {
      return errorFunction.saveErrorAndSend(req, res, err);
    }
  },
};
